import { StyleSheet } from 'react-native';
import { tokens } from './designTokens';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: tokens.colors.warmIvory,
  },
  introShell: {
    flex: 1,
    padding: 24,
    justifyContent: 'space-between',
  },
  introBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  introBlobLarge: {
    position: 'absolute',
    top: 52,
    right: -76,
    width: 238,
    height: 238,
    borderRadius: 84,
    backgroundColor: tokens.colors.selectedSurface,
    transform: [{ rotate: '-18deg' }],
  },
  introBlobSmall: {
    position: 'absolute',
    bottom: 126,
    left: -64,
    width: 176,
    height: 176,
    borderRadius: 68,
    backgroundColor: tokens.colors.softBlush,
    transform: [{ rotate: '24deg' }],
  },
  introContent: {
    flex: 1,
    justifyContent: 'center',
  },
  heroCard: {
    backgroundColor: 'rgba(251, 245, 234, 0.82)',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.10,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  heroSilhouetteRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 28,
  },
  heroSilhouetteBubble: {
    width: 90,
    height: 90,
    borderRadius: 32,
    backgroundColor: tokens.colors.petalWhite,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
  },
  heroSilhouetteBubbleLarge: {
    width: 104,
    height: 104,
    borderRadius: 38,
    backgroundColor: tokens.colors.lightPink,
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    color: tokens.colors.rose,
    fontWeight: '700',
    marginBottom: 8,
  },
  heroTitle: {
    fontSize: 34,
    lineHeight: 44,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  heroBody: {
    marginTop: 16,
    fontSize: 15,
    lineHeight: 24,
    color: tokens.colors.deepMauve,
  },
  heroBullets: {
    marginTop: 24,
    gap: 8,
  },
  heroBullet: {
    fontSize: 15,
    color: tokens.colors.warmMauve,
    lineHeight: 24,
  },
  primaryButton: {
    marginTop: 24,
    backgroundColor: tokens.colors.cornflower,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    shadowColor: '#295FB8',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  primaryButtonDisabled: {
    backgroundColor: tokens.colors.disabled,
  },
  primaryButtonText: {
    color: tokens.colors.softPetal,
    fontSize: 15,
    fontWeight: '700',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButton: {
    marginTop: 16,
    backgroundColor: tokens.colors.softPetal,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  secondaryButtonText: {
    color: tokens.colors.textAccentDark,
    fontSize: 15,
    fontWeight: '700',
  },
  formScrollContent: {
    padding: 24,
    paddingBottom: 40,
  },
  formHeader: {
    marginBottom: 16,
  },
  screenHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  screenHeaderTitle: {
    flex: 1,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.colors.softPetal,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
  },
  iconButtonMuted: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.colors.lightPink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  formBody: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 24,
    color: tokens.colors.mutedMauve,
  },
  section: {
    marginTop: 24,
    backgroundColor: 'rgba(251, 245, 234, 0.84)',
    padding: 16,
    borderRadius: 20,
    ...tokens.shadow.sm,
  },
  sectionTitle: {
    fontSize: 17,
    color: tokens.colors.warmMauve,
    fontWeight: '700',
  },
  sectionBody: {
    marginTop: 8,
    color: tokens.colors.muted,
    fontSize: 15,
    lineHeight: 24,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  speciesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 16,
  },
  speciesCardPressable: {
    width: '48%',
  },
  speciesCard: {
    minHeight: 128,
    borderRadius: 20,
    backgroundColor: tokens.colors.petalWhite,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#8c4a22',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  speciesCardActive: {
    borderColor: tokens.colors.softPink,
    backgroundColor: tokens.colors.lightPink,
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  speciesCardPressed: {
    opacity: 0.88,
  },
  speciesSilhouetteWrap: {
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speciesCardText: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 17,
  },
  speciesCardTextActive: {
    color: tokens.colors.rose,
  },
  selectedSpeciesSummary: {
    marginTop: 12,
    minHeight: 74,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
    backgroundColor: tokens.colors.lightPink,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  selectedSpeciesIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: tokens.colors.visiblePink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedSpeciesTextBlock: {
    flex: 1,
  },
  selectedSpeciesLabel: {
    color: tokens.colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  selectedSpeciesName: {
    marginTop: 4,
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  selectedSpeciesChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  selectedSpeciesChangeText: {
    color: tokens.colors.rose,
    fontSize: 12,
    fontWeight: '800',
  },
  chip: {
    backgroundColor: tokens.colors.petalWhite,
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  chipActive: {
    backgroundColor: tokens.colors.visiblePink,
    borderColor: tokens.colors.rose,
  },
  chipPressed: {
    opacity: 0.82,
  },
  chipText: {
    color: tokens.colors.deepMauve,
    fontWeight: '600',
    fontSize: 15,
  },
  chipTextActive: {
    color: tokens.colors.warmMauve,
  },
  formStepDots: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 16,
  },
  formStepDot: {
    width: 24,
    height: 6,
    borderRadius: 999,
    backgroundColor: tokens.colors.roseQuartz,
  },
  formStepDotActive: {
    width: 36,
    backgroundColor: tokens.colors.softPink,
  },
  swipeShell: {
    flex: 1,
    padding: 24,
  },
  swipeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  swipeTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  resultsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  resultsPillText: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 14,
  },
  insightCard: {
    marginTop: 16,
    backgroundColor: 'rgba(251, 245, 234, 0.84)',
    borderRadius: 20,
    padding: 16,
    ...tokens.shadow.sm,
  },
  insightTitle: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 17,
  },
  insightBody: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  insightMeta: {
    marginTop: 8,
    color: tokens.colors.textMutedWarm,
    fontSize: 12,
  },
  deck: {
    flex: 1,
    justifyContent: 'center',
    marginTop: 16,
  },
  card: {
    backgroundColor: tokens.colors.softPetal,
    borderRadius: 30,
    padding: 24,
    minHeight: 420,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.14,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
    overflow: 'hidden',
  },
  swipeFeedbackOverlay: {
    position: 'absolute',
    top: 16,
    bottom: 16,
    left: 16,
    right: 16,
    zIndex: 5,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  swipeFeedbackLike: {
    backgroundColor: 'rgba(61, 143, 93, 0.22)',
  },
  swipeFeedbackPass: {
    backgroundColor: 'rgba(224, 90, 95, 0.2)',
  },
  swipeFeedbackText: {
    color: tokens.colors.softPetal,
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 2,
  },
  cardGhost: {
    position: 'absolute',
    left: 16,
    right: 16,
    minHeight: 420,
    backgroundColor: tokens.colors.cardGhost,
  },
  cardGhostMiddle: {
    top: 20,
    transform: [{ scale: 0.96 }],
  },
  cardGhostBack: {
    top: 36,
    transform: [{ scale: 0.92 }],
  },
  cardGhostText: {
    marginTop: 12,
    color: tokens.colors.ghostText,
    fontWeight: '700',
    fontSize: 17,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardLabel: {
    color: tokens.colors.rose,
    fontWeight: '700',
    fontSize: 17,
  },
  cardScore: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 17,
  },
  cardName: {
    marginTop: 24,
    fontSize: 34,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  cardReading: {
    marginTop: 8,
    fontSize: 17,
    color: tokens.colors.textMutedWarm,
  },
  cardMeaning: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  metaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  metaChip: {
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  metaChipText: {
    color: tokens.colors.textAccentDark,
    fontWeight: '600',
    fontSize: 12,
  },
  scoreGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 24,
  },
  scorePill: {
    flex: 1,
    backgroundColor: tokens.colors.petalWhite,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    ...tokens.shadow.sm,
  },
  scorePillLabel: {
    color: tokens.colors.textMutedWarm,
    fontSize: 12,
  },
  scorePillValue: {
    marginTop: 8,
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 16,
  },
  actionButton: {
    flex: 1,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    paddingVertical: 16,
  },
  actionPass: {
    backgroundColor: tokens.colors.passSurface,
  },
  actionHold: {
    backgroundColor: tokens.colors.holdSurface,
  },
  actionLike: {
    backgroundColor: tokens.colors.likeSurface,
  },
  actionButtonText: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 17,
  },
  actionButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  summaryCard: {
    marginTop: 16,
    backgroundColor: 'rgba(251, 245, 234, 0.86)',
    borderRadius: 20,
    padding: 16,
    ...tokens.shadow.sm,
  },
  summaryTitle: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 17,
  },
  summaryLine: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  resultsContent: {
    padding: 24,
    paddingBottom: 40,
  },
  resultsLead: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    lineHeight: 24,
    fontSize: 15,
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSoft,
  },
  resultRowRanked: {
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 0,
    borderRadius: 18,
    backgroundColor: tokens.colors.petalWhite,
  },
  resultRowGold: {
    borderLeftWidth: 4,
    borderLeftColor: tokens.colors.gold,
  },
  resultRowSilver: {
    borderLeftWidth: 4,
    borderLeftColor: tokens.colors.silver,
  },
  resultRowBronze: {
    borderLeftWidth: 4,
    borderLeftColor: tokens.colors.bronze,
  },
  rankBadge: {
    minWidth: 54,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.softPink,
    paddingHorizontal: 10,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  rankBadgeGold: {
    backgroundColor: tokens.colors.gold,
  },
  rankBadgeSilver: {
    backgroundColor: tokens.colors.silver,
  },
  rankBadgeBronze: {
    backgroundColor: tokens.colors.bronze,
  },
  rankBadgeText: {
    color: tokens.colors.softPetal,
    fontWeight: '800',
    fontSize: 12,
  },
  preferenceChart: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSoft,
    gap: 8,
  },
  preferenceChartTitle: {
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  preferenceChartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  preferenceChartLabelWrap: {
    width: 80,
  },
  preferenceChartLabel: {
    color: tokens.colors.textMutedWarm,
    fontSize: 12,
    fontWeight: '700',
  },
  preferenceChartTrait: {
    marginTop: 4,
    color: tokens.colors.warmMauve,
    fontSize: 12,
    fontWeight: '800',
  },
  preferenceChartTrack: {
    flex: 1,
    height: 10,
    borderRadius: 12,
    overflow: 'hidden',
  },
  preferenceChartFill: {
    height: 10,
    borderRadius: 12,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(61, 44, 42, 0.42)',
  },
  modalBackdropPressable: {
    flex: 1,
  },
  modalDock: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  nameModalCard: {
    maxHeight: '86%',
    backgroundColor: tokens.colors.softPetal,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    paddingHorizontal: 24,
    paddingTop: 8,
    shadowColor: '#3D2C2A',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -8 },
    elevation: 18,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: tokens.colors.modalHandle,
    marginBottom: 16,
  },
  nameModalContent: {
    paddingBottom: 32,
  },
  modalEyebrow: {
    color: tokens.colors.rose,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  nameModalTitle: {
    marginTop: 8,
    color: tokens.colors.warmMauve,
    fontSize: 34,
    lineHeight: 44,
    fontWeight: '900',
  },
  nameModalReading: {
    marginTop: 4,
    color: tokens.colors.textMutedWarm,
    fontSize: 17,
    fontWeight: '700',
  },
  nameModalMeaning: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  nameModalTagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  nameModalTag: {
    backgroundColor: tokens.colors.softBlush,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  nameModalTagText: {
    color: tokens.colors.textAccentDark,
    fontSize: 12,
    fontWeight: '700',
  },
  nameModalReasonCard: {
    marginTop: 24,
    backgroundColor: tokens.colors.petalWhite,
    borderRadius: 20,
    padding: 16,
    ...tokens.shadow.sm,
  },
  nameModalSectionTitle: {
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  nameModalReasonText: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  nameModalScoreRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  nameModalScoreText: {
    color: tokens.colors.textAccentDark,
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 12,
    fontWeight: '800',
  },
  modalCloseButton: {
    marginTop: 24,
    backgroundColor: tokens.colors.warmMauve,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    paddingVertical: 16,
  },
  modalCloseButtonText: {
    color: tokens.colors.softPetal,
    fontSize: 15,
    fontWeight: '800',
  },
  resultRowText: {
    flex: 1,
  },
  resultRowName: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 17,
  },
  resultRowBody: {
    marginTop: 8,
    color: tokens.colors.mutedMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  resultRowAction: {
    color: tokens.colors.rose,
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 1,
  },
  resultRowActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  emptyCard: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCardTitle: {
    fontSize: 24,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  emptyCardBody: {
    marginTop: 12,
    color: tokens.colors.mutedMauve,
    fontSize: 15,
  },
  loadingShell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingLogo: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: tokens.colors.lightPink,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  loadingText: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    fontWeight: '700',
  },
  loadingErrorText: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
  },
});
