import { StyleSheet } from 'react-native';
import { tokens } from './designTokens';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: tokens.colors.warmIvory,
  },

  // ── Welcome Screen: Premium Matching App Style ──
  welcomeShell: {
    flex: 1,
    paddingHorizontal: 32,
    paddingTop: 60,
    paddingBottom: 40,
    justifyContent: 'space-between',
    flexDirection: 'column',
  },
  welcomeBrandArea: {
    alignItems: 'center',
  },
  welcomeLogoRow: {
    marginBottom: 20,
  },
  welcomeLogoText: {
    fontSize: 28,
    fontWeight: '800',
    color: tokens.colors.warmMauve,
    letterSpacing: 2,
  },
  welcomeTagline: {
    fontSize: 30,
    lineHeight: 40,
    color: tokens.colors.deepMauve,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 16,
  },
  welcomeSub: {
    fontSize: 15,
    lineHeight: 22,
    color: tokens.colors.mutedMauve,
    textAlign: 'center',
    fontWeight: '400',
  },
  welcomeActions: {
    alignItems: 'center',
  },
  welcomeCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.cornflower,
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 999,
    minWidth: 260,
    shadowColor: '#295FB8',
    shadowOpacity: 0.2,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  welcomeCtaText: {
    color: tokens.colors.softPetal,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  welcomeSignIn: {
    fontSize: 14,
    color: tokens.colors.rose,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  welcomeTerms: {
    marginTop: 24,
    fontSize: 11,
    lineHeight: 16,
    color: tokens.colors.mutedMauve,
    textAlign: 'center',
    maxWidth: 280,
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    color: tokens.colors.rose,
    fontWeight: '700',
    marginBottom: 8,
  },
  primaryButton: {
    marginTop: 24,
    backgroundColor: tokens.colors.cornflower,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    shadowColor: '#295FB8',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  primaryButtonDisabled: {
    backgroundColor: tokens.colors.disabled,
  },
  primaryButtonText: {
    color: tokens.colors.softPetal,
    fontSize: 15,
    fontWeight: '700',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButton: {
    marginTop: 16,
    backgroundColor: tokens.colors.softPetal,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  secondaryButtonText: {
    color: tokens.colors.textAccentDark,
    fontSize: 15,
    fontWeight: '700',
  },
  formScrollContent: {
    padding: 24,
    paddingBottom: 40,
  },
  formHeader: {
    marginBottom: 16,
  },
  screenHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  screenHeaderTitle: {
    flex: 1,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.colors.softPetal,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
  },
  iconButtonMuted: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.colors.lightPink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  formBody: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 24,
    color: tokens.colors.mutedMauve,
  },
  section: {
    marginTop: 24,
    backgroundColor: 'rgba(251, 245, 234, 0.84)',
    padding: 16,
    borderRadius: 20,
    ...tokens.shadow.sm,
  },
  sectionTitle: {
    fontSize: 17,
    color: tokens.colors.warmMauve,
    fontWeight: '700',
  },
  sectionBody: {
    marginTop: 8,
    color: tokens.colors.muted,
    fontSize: 15,
    lineHeight: 24,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  speciesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 16,
  },
  speciesCardPressable: {
    width: '48%',
  },
  speciesCard: {
    minHeight: 128,
    borderRadius: 20,
    backgroundColor: tokens.colors.petalWhite,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#8c4a22',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  speciesCardActive: {
    borderColor: tokens.colors.softPink,
    backgroundColor: tokens.colors.lightPink,
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  speciesCardPressed: {
    opacity: 0.88,
  },
  speciesSilhouetteWrap: {
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speciesCardText: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 17,
  },
  speciesCardTextActive: {
    color: tokens.colors.rose,
  },
  selectedSpeciesSummary: {
    marginTop: 12,
    minHeight: 74,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
    backgroundColor: tokens.colors.lightPink,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  selectedSpeciesIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: tokens.colors.visiblePink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedSpeciesTextBlock: {
    flex: 1,
  },
  selectedSpeciesLabel: {
    color: tokens.colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  selectedSpeciesName: {
    marginTop: 4,
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  selectedSpeciesChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  selectedSpeciesChangeText: {
    color: tokens.colors.rose,
    fontSize: 12,
    fontWeight: '800',
  },
  chip: {
    backgroundColor: tokens.colors.petalWhite,
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  chipActive: {
    backgroundColor: tokens.colors.visiblePink,
    borderColor: tokens.colors.rose,
  },
  chipPressed: {
    opacity: 0.82,
  },
  chipText: {
    color: tokens.colors.deepMauve,
    fontWeight: '600',
    fontSize: 15,
  },
  chipTextActive: {
    color: tokens.colors.warmMauve,
  },
  formStepDots: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 16,
  },
  formStepDot: {
    width: 24,
    height: 6,
    borderRadius: 999,
    backgroundColor: tokens.colors.roseQuartz,
  },
  formStepDotActive: {
    width: 36,
    backgroundColor: tokens.colors.softPink,
  },
  swipeShell: {
    flex: 1,
    padding: 24,
  },
  swipeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  swipeTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  resultsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  resultsPillText: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 14,
  },
  insightCard: {
    marginTop: 16,
    backgroundColor: 'rgba(251, 245, 234, 0.84)',
    borderRadius: 20,
    padding: 16,
    ...tokens.shadow.sm,
  },
  insightTitle: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 17,
  },
  insightBody: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  insightMeta: {
    marginTop: 8,
    color: tokens.colors.textMutedWarm,
    fontSize: 12,
  },
  deck: {
    flex: 1,
    justifyContent: 'center',
    marginTop: 16,
  },
  cardGestureTarget: {
    minHeight: 420,
    justifyContent: 'center',
  },
  activeSwipeCardLayer: {
    zIndex: 2,
  },
  card: {
    backgroundColor: tokens.colors.softPetal,
    borderRadius: 30,
    padding: 24,
    paddingTop: 0,
    minHeight: 420,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.14,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
    overflow: 'hidden',
  },
  cardAccentBar: {
    height: 6,
    marginHorizontal: -24,
    marginBottom: 18,
  },
  swipeFeedbackOverlay: {
    position: 'absolute',
    top: 16,
    bottom: 16,
    left: 16,
    right: 16,
    zIndex: 5,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
  },
  swipeFeedbackLike: {
    backgroundColor: 'rgba(61, 143, 93, 0.18)',
  },
  swipeFeedbackLikeBorder: {
    borderColor: 'rgba(61, 143, 93, 0.55)',
  },
  swipeFeedbackLikeStamp: {
    color: 'rgba(61, 143, 93, 0.85)',
    fontSize: 44,
    fontWeight: '900',
    letterSpacing: 3,
    transform: [{ rotate: '-15deg' }],
  },
  swipeFeedbackPass: {
    backgroundColor: 'rgba(224, 90, 95, 0.18)',
  },
  swipeFeedbackPassBorder: {
    borderColor: 'rgba(224, 90, 95, 0.5)',
  },
  swipeFeedbackPassStamp: {
    color: 'rgba(224, 90, 95, 0.8)',
    fontSize: 44,
    fontWeight: '900',
    letterSpacing: 3,
    transform: [{ rotate: '12deg' }],
  },
  swipeFeedbackText: {
    color: tokens.colors.softPetal,
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 2,
  },
  // Swipe-linked background tint
  swipeBgTint: {
    position: 'absolute',
    top: -100,
    left: -100,
    right: -100,
    bottom: -100,
    backgroundColor: tokens.colors.softPink,
  },
  cardGhost: {
    position: 'absolute',
    left: 16,
    right: 16,
    minHeight: 420,
    backgroundColor: tokens.colors.cardGhost,
  },
  // 5-card perspective stack — each deeper level gets smaller + lower
  cardGhost2: {
    top: 14,
    transform: [{ scale: 0.965 }],
  },
  cardGhost3: {
    top: 28,
    transform: [{ scale: 0.93 }],
  },
  cardGhost4: {
    top: 42,
    transform: [{ scale: 0.895 }],
  },
  cardGhost5: {
    top: 54,
    transform: [{ scale: 0.86 }],
    opacity: 0.8,
  },
  cardGhostText: {
    marginTop: 12,
    color: tokens.colors.ghostText,
    fontWeight: '700',
    fontSize: 17,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardSpeciesPill: {
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  cardSpeciesPillText: {
    fontWeight: '700',
    fontSize: 12,
  },
  cardLabel: {
    color: tokens.colors.rose,
    fontWeight: '700',
    fontSize: 17,
  },
  cardScore: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 17,
  },
  cardName: {
    marginTop: 24,
    fontSize: 34,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  cardReading: {
    marginTop: 8,
    fontSize: 17,
    color: tokens.colors.textMutedWarm,
  },
  cardMeaning: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  metaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  metaChip: {
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  metaChipText: {
    color: tokens.colors.textAccentDark,
    fontWeight: '600',
    fontSize: 12,
  },
  toneChip: {
    backgroundColor: tokens.colors.roseQuartz,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  toneChipText: {
    color: tokens.colors.mutedMauve,
    fontWeight: '700',
    fontSize: 11,
  },
  scoreGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 24,
  },
  scorePill: {
    flex: 1,
    backgroundColor: tokens.colors.petalWhite,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    ...tokens.shadow.sm,
  },
  scorePillLabel: {
    color: tokens.colors.textMutedWarm,
    fontSize: 12,
  },
  scorePillValue: {
    marginTop: 8,
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 16,
  },
  actionButton: {
    flex: 1,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    paddingVertical: 16,
  },
  actionPass: {
    backgroundColor: tokens.colors.passSurface,
  },
  actionHold: {
    backgroundColor: tokens.colors.holdSurface,
  },
  actionLike: {
    backgroundColor: tokens.colors.likeSurface,
  },
  actionButtonText: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 17,
  },
  actionButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  summaryCard: {
    marginTop: 16,
    backgroundColor: 'rgba(251, 245, 234, 0.86)',
    borderRadius: 20,
    padding: 16,
    ...tokens.shadow.sm,
  },
  summaryTitle: {
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    fontSize: 17,
  },
  summaryLine: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  resultsContent: {
    padding: 24,
    paddingBottom: 40,
  },
  resultsLead: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    lineHeight: 24,
    fontSize: 15,
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSoft,
  },
  resultRowRanked: {
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 0,
    borderRadius: 18,
    backgroundColor: tokens.colors.petalWhite,
  },
  resultRowGold: {
    borderLeftWidth: 4,
    borderLeftColor: tokens.colors.gold,
  },
  resultRowSilver: {
    borderLeftWidth: 4,
    borderLeftColor: tokens.colors.silver,
  },
  resultRowBronze: {
    borderLeftWidth: 4,
    borderLeftColor: tokens.colors.bronze,
  },
  rankBadge: {
    minWidth: 54,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.softPink,
    paddingHorizontal: 10,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  rankBadgeGold: {
    backgroundColor: tokens.colors.gold,
  },
  rankBadgeSilver: {
    backgroundColor: tokens.colors.silver,
  },
  rankBadgeBronze: {
    backgroundColor: tokens.colors.bronze,
  },
  rankBadgeText: {
    color: tokens.colors.softPetal,
    fontWeight: '800',
    fontSize: 12,
  },
  preferenceChart: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSoft,
    gap: 8,
  },
  preferenceChartTitle: {
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  preferenceChartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  preferenceChartLabelWrap: {
    width: 80,
  },
  preferenceChartLabel: {
    color: tokens.colors.textMutedWarm,
    fontSize: 12,
    fontWeight: '700',
  },
  preferenceChartTrait: {
    marginTop: 4,
    color: tokens.colors.warmMauve,
    fontSize: 12,
    fontWeight: '800',
  },
  preferenceChartTrack: {
    flex: 1,
    height: 10,
    borderRadius: 12,
    overflow: 'hidden',
  },
  preferenceChartFill: {
    height: 10,
    borderRadius: 12,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(61, 44, 42, 0.42)',
  },
  modalBackdropPressable: {
    flex: 1,
  },
  modalDock: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  nameModalCard: {
    maxHeight: '86%',
    backgroundColor: tokens.colors.softPetal,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    paddingHorizontal: 24,
    paddingTop: 8,
    shadowColor: '#3D2C2A',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -8 },
    elevation: 18,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: tokens.colors.modalHandle,
    marginBottom: 16,
  },
  nameModalContent: {
    paddingBottom: 32,
  },
  modalEyebrow: {
    color: tokens.colors.rose,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  nameModalTitle: {
    marginTop: 8,
    color: tokens.colors.warmMauve,
    fontSize: 34,
    lineHeight: 44,
    fontWeight: '900',
  },
  nameModalReading: {
    marginTop: 4,
    color: tokens.colors.textMutedWarm,
    fontSize: 17,
    fontWeight: '700',
  },
  nameModalMeaning: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  nameModalTagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  nameModalTag: {
    backgroundColor: tokens.colors.softBlush,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  nameModalTagText: {
    color: tokens.colors.textAccentDark,
    fontSize: 12,
    fontWeight: '700',
  },
  nameModalReasonCard: {
    marginTop: 24,
    backgroundColor: tokens.colors.petalWhite,
    borderRadius: 20,
    padding: 16,
    ...tokens.shadow.sm,
  },
  nameModalSectionTitle: {
    color: tokens.colors.warmMauve,
    fontSize: 17,
    fontWeight: '800',
  },
  nameModalReasonText: {
    marginTop: 8,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  nameModalScoreRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  nameModalScoreText: {
    color: tokens.colors.textAccentDark,
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 12,
    fontWeight: '800',
  },
  modalCloseButton: {
    marginTop: 24,
    backgroundColor: tokens.colors.warmMauve,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    paddingVertical: 16,
  },
  modalCloseButtonText: {
    color: tokens.colors.softPetal,
    fontSize: 15,
    fontWeight: '800',
  },
  resultRowText: {
    flex: 1,
  },
  resultRowName: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 17,
  },
  resultRowBody: {
    marginTop: 8,
    color: tokens.colors.mutedMauve,
    fontSize: 15,
    lineHeight: 24,
  },
  resultRowAction: {
    color: tokens.colors.rose,
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 1,
  },
  resultRowActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  emptyCard: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCardTitle: {
    fontSize: 24,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  emptyCardBody: {
    marginTop: 12,
    color: tokens.colors.mutedMauve,
    fontSize: 15,
  },
  loadingShell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingLogo: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: tokens.colors.lightPink,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  loadingText: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    fontWeight: '700',
  },
  loadingErrorText: {
    marginTop: 16,
    color: tokens.colors.deepMauve,
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
  },
  demoCardPreview: {
    marginBottom: 20,
    alignItems: 'center',
  },
  demoCardTrack: {
    width: '100%',
    maxWidth: 280,
    alignItems: 'center',
  },
  demoCard: {
    width: '100%',
    backgroundColor: tokens.colors.softPetal,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.10,
    shadowRadius: 18,
    shadowOffset: { width: 4, height: 8 },
    elevation: 8,
    borderWidth: 1,
    borderColor: tokens.colors.roseQuartz,
  },
  demoCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  demoCardLabel: {
    color: tokens.colors.rose,
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 1,
  },
  demoCardName: {
    fontSize: 28,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
  },
  demoCardReading: {
    marginTop: 4,
    color: tokens.colors.textMutedWarm,
    fontSize: 15,
    fontWeight: '600',
  },
  demoCardMeaning: {
    marginTop: 10,
    color: tokens.colors.deepMauve,
    fontSize: 13,
    lineHeight: 20,
  },
  demoCardMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 12,
  },
  demoChip: {
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  demoChipText: {
    color: tokens.colors.textAccentDark,
    fontSize: 11,
    fontWeight: '700',
  },
  demoSwipeHint: {
    marginTop: 14,
    alignItems: 'flex-end',
  },
  demoSwipeHintText: {
    color: tokens.colors.cornflower,
    fontSize: 24,
    fontWeight: '800',
    opacity: 0.5,
  },
  // ── Progress Bar ──
  swipeProgressWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  swipeProgressTrack: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: tokens.colors.roseQuartz,
    overflow: 'hidden',
  },
  swipeProgressFill: {
    height: 4,
    borderRadius: 999,
    backgroundColor: tokens.colors.softPink,
  },
  swipeProgressText: {
    color: tokens.colors.mutedMauve,
    fontSize: 12,
    fontWeight: '700',
    minWidth: 52,
    textAlign: 'right',
  },
  // ── Undo Button ──
  undoButton: {
    alignSelf: 'center',
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: tokens.colors.softBlush,
  },
  undoButtonText: {
    color: tokens.colors.textAccentDark,
    fontSize: 12,
    fontWeight: '700',
  },
  // ── First Swipe Hint ──
  firstSwipeHint: {
    position: 'absolute',
    bottom: 120,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  firstSwipeHintBubble: {
    backgroundColor: tokens.colors.cornflower,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: '#295FB8',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  firstSwipeHintText: {
    color: tokens.colors.softPetal,
    fontSize: 13,
    fontWeight: '700',
  },
  // ── Quick Form (species picker only) ──
  quickFormShell: {
    flex: 1,
    padding: 24,
    justifyContent: 'space-between',
  },
  quickFormTitle: {
    fontSize: 26,
    lineHeight: 34,
    color: tokens.colors.warmMauve,
    fontWeight: '800',
    marginBottom: 24,
  },
  quickFormBody: {
    flex: 1,
  },
  quickFormBodyInner: {
    flexGrow: 1,
    paddingTop: 4,
    paddingBottom: 8,
  },
  quickFormHint: {
    fontSize: 14,
    lineHeight: 20,
    color: tokens.colors.mutedMauve,
    marginBottom: 16,
  },
  quickFormSpeciesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 24,
  },
  quickFormSpeciesCard: {
    width: '47%',
    minHeight: 132,
    borderRadius: 20,
    backgroundColor: tokens.colors.petalWhite,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#8c4a22',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  quickFormSpeciesCardActive: {
    borderColor: tokens.colors.cornflower,
    backgroundColor: tokens.colors.softPetal,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  quickFormSpeciesSilhouette: {
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickFormSpeciesLabel: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 15,
  },
  quickFormSpeciesLabelActive: {
    color: tokens.colors.cornflower,
    fontWeight: '800',
  },
  quickFormSpeciesCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  quickFormFooter: {
    marginTop: 24,
    paddingBottom: 8,
  },
  // ── Filter Sheet ──
  filterSheetScroll: {
    paddingBottom: 32,
  },
  filterSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  filterSheetTitle: {
    color: tokens.colors.warmMauve,
    fontSize: 20,
    fontWeight: '800',
  },
  filterSheetCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.softBlush,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.lightPink,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  filterBarButtonText: {
    color: tokens.colors.warmMauve,
    fontWeight: '700',
    fontSize: 13,
  },
  // ── Swipe Header slim ──
  swipeHeaderSlim: {
    marginBottom: 8,
  },
  // ── Tinder-style circle action buttons ──
  circleActionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    marginTop: 12,
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  circleActionButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8c4a22',
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  circleActionPass: {
    backgroundColor: '#E05A5F',
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  circleActionLike: {
    backgroundColor: '#3D8F5D',
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  circleActionHold: {
    backgroundColor: tokens.colors.softBlush,
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  circleActionUndo: {
    backgroundColor: tokens.colors.softBlush,
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  circleActionInfo: {
    backgroundColor: tokens.colors.softBlush,
    width: 48,
    height: 48,
    borderRadius: 24,
  },
});
